apiVersion: v1
kind: Service
metadata:
  name: micro-meeting-service
spec:
  type: {{ .Values.service.type }}
  ports:
    # the port that this service should serve on
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.deployment.containerProtocol}}    
    targetPort: {{ .Values.deployment.containerPort}}
    name: http
  selector:
    microservice: {{ .Values.deployment.name}}
    
